### ISSUE TITLE
No hay nada

### ISSUE THREAD

**Issue by jesus-ale43** [dzlib/lapcord-server#1]
trabajen

**Comment by DexSlender** [comment]
XD

**Comment by Hyduez** [comment]
@all-contributors please add @DexSlender for code, ideas & planning and tests

**Comment by Hyduez** [comment]
@all-contributors
please add @Hyduez for style and maintenance
please add @jesus-ale43 for code, desing and tests

**Comment by Hyduez** [comment]
@all-contributors please add @jesus-ale43 for code, design and test

**Comment by Hyduez** [comment]
@all-contributors please add @jesus-ale43 for code, design and tests.

**Comment by Hyduez** [comment]
idc

**Comment by Hyduez** [comment]
@all-contributors please add @jesus-ale43 for code, design and tests.

**Comment by Hyduez** [comment]
NOT AGAIN PLEASE 😭💀💯💯💯

**Comment by jesus-ale43** [comment]
ya trabajamos
